---
title: "Untitled"
output: html_document
---

```{r}
## Load Packages -----
library("shiny")
library("leaflet")
library("dplyr")
library("RColorBrewer")
library("stringr")
library("parcoords")
library("ggplot2")
library("reshape2")
library("geosphere")
library("ggthemes")
library("formattable")
library("base64enc")
library("plotly")
library(GGally)
library(tidyverse)
#devtools::install_github("timelyportfolio/parcoords")


##Import Data -----
#customer Data
data_customer <- read.csv("../../output/combind_data.csv")



server <- function(input, output) {
  ##For display of customer satisfaction in Tab
  
  #plot for combined statistics
  output$combineplot <- renderPlot({
    if(length(input$carrier == 0)){
      plot(0,xaxt='n',yaxt='n',bty='n',pch='',ylab='',xlab='')
    }
    if(length(input$carrier > 0)){
      # generate an rnorm distribution and plot it
      carr_name <- input$carrier
      carr_row <- data_customer$airline %in% carr_name
      carr_data <- data_customer[carr_row, c(2,3,4)]
      ggparcoord(carr_data, columns = 2:3, groupColumn = 1)
    }
  })
  
  #plots for seperate statistics
  output$luggageplot=renderPlot({
    ggplot(data_customer)+
  layer(mapping = aes(x = fct_reorder(airline,`missing.luggage.per.1000.passangers`), y =`missing.luggage.per.1000.passangers`),
        params = list(fill = "lightblue"),
	       geom = "bar",stat = "identity", position = "identity")+
  theme(axis.text.x = element_text(size = 8,hjust=1,vjust = 1, angle = 20))+
      labs(x='airline')
  })
  

  output$complaintplot=renderPlot({
    ggplot(data_customer)+
  layer(mapping = aes(x = fct_reorder(airline,`customer.complaint`), y =`customer.complaint`),
        params = list(fill = "lightgreen"),
	       geom = "bar",stat = "identity", position = "identity")+
  theme(axis.text.x = element_text(size = 8,hjust=1,vjust = 1, angle = 20))+
      labs(x='airline')

  })

  output$voluntaryplot=renderPlot({
    ggplot(data_customer)+
  geom_point(mapping=aes(x=airline,y=Voluntary.permillage,color='voluntary'))+
  theme(axis.text.x = element_text(size = 8,hjust=1,vjust = 1, angle = 45))+
      labs(x='airline')
  })

 output$involuntaryplot=renderPlot({
   ggplot(data_customer)+
  geom_point(mapping=aes(x=airline,y=Involuntary.permillage,color='involuntary'))+
  theme(axis.text.x = element_text(size = 8,hjust=1,vjust = 1, angle = 45))+
      labs(x='airline')
 })
  
}
```

```{r}
## Load Packages -----
library("shiny")
library("leaflet")
library("dplyr")
library("RColorBrewer")
library("stringr")
library("parcoords")
library("ggplot2")
library("reshape2")
library("geosphere")
library("ggthemes")
library("formattable")
library("base64enc")
library("plotly")
library(tidyverse)
#devtools::install_github("timelyportfolio/parcoords")

##customer satisfaction-----
tab1 <- navbarMenu("Customer Satisfaction",
                   
                   
                   
                   #tabpanel1
                   tabPanel(title = "Combined Statistics",
                            fluidRow( wellPanel(style = "overflow-y:scroll;  height: 500px; opacity: 0.9; background-color: #ffffff;",
                                                column(width = 9, plotOutput("combineplot"),
                                                       tags$a(href = "https://www.transtats.bts.gov/","2015-2017 Data,Source:https://www.transtats.bts.gov/")
                                                       
                                                ),
                                                column(width = 3, checkboxGroupInput("carrier", "Choose a Airline:",
                                                                                     choices = c('ALASKA AIRLINES','AMERICAN AIRLINES','DELTA AIR LINES','ENVOY AIR','EXPRESSJET AIRLINES','FRONTIER AIRLINES','HAWAIIAN AIRLINES','JETBLUE AIRWAYS','SKYWEST AIRLINES','SOUTHWEST AIRLINES','SPIRIT AIRLINES','UNITED AIRLINES'),
                                                                                     selected = "AMERICAN AIRLINES"))
                                                
                                                
                            ))),
                   

                   
                   #tabpanel 2
                tabPanel(title = "Seperate Statistics",
                            fluidRow( wellPanel(style = "overflow-y:scroll;  height: 500px; opacity: 0.9; background-color: #ffffff;",
                                                column(width = 12, 
                                                       plotOutput("luggageplot"),
                                                       plotOutput("complaintplot"),
                                                       plotOutput("voluntaryplot"),
                                                       plotOutput("involuntaryplot")
                                                       
                                                       
                                                ))))
                            
                   )



## UI 
ui <- shinyUI(navbarPage(title = strong("AirPlan"),
                         tab1
))

```

```{r}
shinyApp(ui,server)
```

