---
title: "Untitled"
author: "YueZhang yz3383"
date: "2/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate) # used to extract year from date
library(shiny)
library(plotly)

# Accidents
airport.data <- read.csv("../data/accident_state.csv")
month.data <- read.csv("../data/accident_month.csv")
# aircraft.make <- read.csv("../data/accident_aircraft.csv")
# operator <- read.csv("../data/accident_operator.csv")
state.names <- unique(airport.data$Event.State)
```

```{r}
tab1 <-   tabPanel("Accident Number by year",
                   sidebarLayout(
                     sidebarPanel(
                        sliderInput("year",
                                    "Different year:",
                                    min = 1978,
                                    max = 2018,
                                    value = 2008)
                        ),
    
                     mainPanel(
                       plotlyOutput("accident.year"),
                       verbatimTextOutput("click"))
                     ),
                   
                   h3("Accident Month",
                      style="color:	white",
                      align="center",
                      astyle="font-family:helvetica;"),
                      fluidRow( wellPanel(style = "overflow-y:scroll; height: 480px; opacity: 0.9; background-color: #ffffff;",
                                          plotOutput("accident.month"),
                                                p("Footnote: Number in the circle represents the number of accident for airlines"),
                                                
                                                tags$a(href = "https://www.transtats.bts.gov/","2000-2017 Data, Source:https://www.transtats.bts.gov/")
                            )
                   ))

# tab2 <- tabPanel()

ui <- fluidPage(navbarPage(title = strong("AirPlan2.0"),
                           tab1
                           # ,tab2
                           )
                )
```

```{r}
server <- function(input, output, session) {
  
  output$accident.year <- renderPlotly({
    # specify some map projection/options
    g <- list(
      scope = 'usa',
      projection = list(type = 'albers usa'),
      lakecolor = toRGB('white')
    )
    
    plotdata <- airport.data %>%
      filter(year == input$year)
    
    plot_ly(z = plotdata$count, locations = plotdata$Event.State,
            type = 'choropleth', locationmode = 'USA-states') %>%
      layout(geo = g)
  })
  
  output$click <- renderPrint({
    d <- event_data("plotly_click")
    # if (is.null(d)) "Click on a state to view event data" else d
  })
  
  output$accident.month <- renderPlotly(
    month.data %>%
      plot_ly(
        x = ~month, 
        y = ~count, 
        frame = ~year, 
        text = ~count, 
        hoverinfo = "text",
        linetype = I("dash"),
        name = 'Accident Number'
      )
  )
}

shinyApp(ui, server)
```